- name: "install :: updates package lists"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: "install :: upgrades package lists"
  become: true
  ansible.builtin.apt:
    upgrade: full
    force_apt_get: true

- name: "install :: adds the official Google key"
  become: true
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key"
    state: present
    keyring: /etc/apt/sources.list.d/kubernetes.list

- name: "install :: adds the official Kubernetes repository"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present

- name: "install :: updates package lists"
  become: true
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: "install :: installs the Kubernetes packages"
  become: true
  ansible.builtin.apt:
    pkg:
      - kubeadm=1.28.*
      - kubelet=1.28.*
      - kubernetes-cni
    force_apt_get: true
